sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
os:
  - linux
  - osx
after_failure:
  - tree -h
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=tokio_kafka=trace
script:
  - (test $TRAVIS_RUST_VERSION != "nightly" || cargo build --features clippy)
  - (test $TRAVIS_RUST_VERSION == "nightly" || cargo build)
  - cargo test --verbose
